Field: true
World: world
AreaPos1: 100,1,100
AreaPos2: 200,128,200
Present:
    - diamond-pickaxe,イベント参加賞,34-5,35-5
RePresent: 2500
Repair: 100

# Count Stones
PointStone:
    - STONE,1
    - GRANITE,3
    - DIORITE,3
    - ANDESITE,3
    - GRAVEL,2
    - NETHERRACK,1
    - QUARTZ_ORE,5
    - SOUL_SAND,2
    - DIRT,2
    - GRASS,2
    - DIAMOND_ORE,5
    - EMERALD_ORE,10
    - IRON_ORE,4
    - GOLD_ORE,4
    - REDSTONE_ORE,3
    - COAL_ORE,3
    - LAPIS_ORE,4
    - SMOOTH_BRICK,-10
    - NETHER_BRICK,-10
