#   Premises Event Configuration File

#   Debug ( max / full / Default:normal / none )
Debug: normal

#   イベントエリアを限定する場合設定
#   Fieldがfalseの場合サーバー全体が対象となる
#   Whether to perform a field check
#   If it is false, it will be the entire server
EventName: EventName
Field: true
World: world
AreaPos1: 200,50,100
AreaPos2: 100,2,200

#   イベント難易度 (Easy/Normal/Hard)
#   Easy :      ペナルティブロックは破壊できない＋警告
#   Normal :    ペナルティブロックの警告メッセージのみ表示
#   Hard :      ペナルティブロックの警告も無い（参加者の注意力が要求される）
Difficulty: Normal

#   下層ブロックのみの掘削制限
#   None :      制限しない
#   Warning :   注意喚起チャットメッセージ
#   Block :     破壊不能
#   None 以外は、採掘速度低下１０秒のペナルティ発動
UpperBlock: Warning

#   他者エリア掘削の警告表示
#   true :      警告する
#   false :     警告しない
PlayerAlarm: true

#   参加者以外のブロック破壊を許すか/Free Block Break
#   true = All Player
#   false = EntryPlayer Only
FreeBreak: true

#   参加者以外のブロック設置を許すか/Allow block placement for non-participant
#   true = All Player/全プレイヤー
#   false = Entry Player/参加プレイヤーのみ
FreePlace: false

#   登録ブロック以外の設置を許すか/Permit installation other than registration block
#   true = All Blocks
#   false = Event Block Only
SpecifiedPlace: true

#   イベントツールのみ破壊可能とするか/Special Tools Only Break
ToolBreak: false

#   ブロックのカウントがゼロの時、設置可能とするか/Block Count Zero Place
ZeroPlace: false

#   イベントアイテムを再配布するのに必要なスコアーコスト/Required score for redistributing gift Tool Items
RePresent: 2000

#   イベントツールのアップデートに必要なスコアーコスト/Score required for event tool update
UpdateCost: 0

#   クリエイティブモードでのカウント停止/CreativeCount True = no Count False = Alwayes Count
CreativeCount: true

#   ツールの耐久値警告設定（残り％）/Percentage of endurance value that can be updated ( 0.1 = 10% )
Repair: 0.1

#   重要メッセージを画面中央に表示するか/Player.sendTitle Status
sendTitle: true

#   スコア達成アナウンス設定
#   Notice:コンソールのみ   Broadcast:サーバーチャット
#   Player's score arrival notice
#   0(zero) is disable
ScoreNotice: 10000
ScoreBroadcast: 100000

#   ScoreBroadcast達成時に実行されるコマンド一覧/When score set for broadcast, console command execution setting
BroadcastCommand:
    - discord broadcast %message%
    - give %player% BREAD 10

#   イベント参加時にプレイヤーに表示されるメッセージ/Join Message
JOIN_MESSAGE: "§eイベントルールに則って参加してください [ §ahttps://bit.ly/2Tf7tL8§e ]"

#   イベント参加時に自動配布されるツールの種類/Present Tool Item Setting
EventToolName: §bイベントツール
Present:
    - IRON_PICKAXE
    - IRON_SPADE
    - IRON_AXE

#   イベントに関するブロックのポイント設定/Count Stones
#   ポイントマイナス値はペナルティブロック扱い
#   ポイントゼロ値は足場ブロック扱い
PointStone:
    - COBBLESTONE,0
    - OBSIDIAN,10
    - SANDSTONE,1
    - STAINED_CLAY,1
    - HARD_CLAY,1
    - STONE,1
    - SAND,1
    - GRANITE,1
    - DIORITE,1
    - ANDESITE,1
    - GRAVEL,1
    - NETHERRACK,1
    - MAGMA,1
    - GLOWSTONE,1
    - QUARTZ_ORE,1
    - SOUL_SAND,1
    - DIRT,1
    - GRASS,1
    - DIAMOND_ORE,5
    - EMERALD_ORE,10
    - IRON_ORE,1
    - GOLD_ORE,2
    - REDSTONE_ORE,1
    - GLOWING_REDSTONE_ORE,1
    - COAL_ORE,1
    - LAPIS_ORE,1
    - SMOOTH_BRICK,-10000
    - NETHER_BRICK,-10000
    - BONE_BLOCK,-10000
