#   Whether to perform a field check
#   If it is false, it will be the entire server
EventName: EventName
Field: true
World: world
AreaPos1: 200,50,100
AreaPos2: 100,2,200

#   Free Block Break
#   true = All Player
#   false = EntryPlayer Only
FreeBreak: true

#   Special Pickaxe Only Break
ToolBreak: false

#   Required score for redistributing gift Tool Items
RePresent: 2000

#   Score required for event tool update
UpdateCost: 0

#   CreativeCount True = no Count False = Alwayes Count
CreativeCount: true

#   Percentage of endurance value that can be updated ( 0.1 = 10% )
Repair: 0.1

#   Present Tool Item Setting
EventToolName: §bイベントツール
Present:
    - IRON_PICKAXE
    - IRON_SPADE
    - IRON_AXE

# Count Stones
PointStone:
    - OBSIDIAN,10
    - SANDSTONE,1
    - STAINED_CLAY,1
    - HARD_CLAY,1
    - STONE,1
    - SAND,1
    - GRANITE,1
    - DIORITE,1
    - ANDESITE,1
    - GRAVEL,1
    - NETHERRACK,1
    - MAGMA,1
    - GLOWSTONE,1
    - QUARTZ_ORE,1
    - SOUL_SAND,1
    - DIRT,1
    - GRASS,1
    - DIAMOND_ORE,5
    - EMERALD_ORE,10
    - IRON_ORE,1
    - GOLD_ORE,2
    - REDSTONE_ORE,1
    - GLOWING_REDSTONE_ORE,1
    - COAL_ORE,1
    - LAPIS_ORE,1
    - SMOOTH_BRICK,-10000
    - NETHER_BRICK,-10000
    - BONE_BLOCK,-10000
