name: PremisesEvent
version: 0.4
main: com.mycompany.premisesevent.PremisesEvent
description: Premises Event Control plugin
author: Kumaisu
database: true
commands:
    premises:
        description: Premises Event Control Command
        aliases: pe
        usage: /<command> help
permissions:
    Premises.broadcast:
        description: Broadcast announce
        default: true
    Premises.admin:
        description: Command Permission
        default: op
