name: PremisesEvent
version: '1.0.1'
main: io.github.kumaisu.premisesevent.PremisesEvent
api-version: '1.21'
description: Premises Event Control plugin
author: NineTailedFox
database: true
commands:
    premises:
        description: Premises Event Control Command
        aliases: pe
        usage: /<command> help
    area:
        description: Area Control Command
        aliases: pea
        usage: /<command> help
permissions:
    Premises.broadcast:
        description: Broadcast announce
        default: true
    Premises.admin:
        description: Command Permission
        default: op
    Premises.warning:
        description: rule warning message
