name: PremisesEvent
version: 0.0.1
main: com.mycompany.premisesevent.PremisesEvent
description: Premises Event Control plugin
author: Kumaisu
database: true
commands:
    premises:
        description: Premises Event Control Command
        aliases: pec
        usage: |
            /<command> join
            /<command> status [PlayerName]
            /<command> get
            /<command> update
