main: com.mycompany.premisesevent.PremisesEvent
name: PremisesEvent
version: 0.8.6
description: Premises Event Control plugin
author: Kumaisu
database: true
api-version: 1.14
commands:
    premises:
        description: Premises Event Control Command
        aliases: pe
        usage: /<command> help
    area:
        description: Area Control Command
        aliases: pea
        usage: /<command> help
permissions:
    Premises.broadcast:
        description: Broadcast announce
        default: true
    Premises.admin:
        description: Command Permission
        default: op
    Premises.warning:
        description: rule warning message
